print_info() {
    info title
    info underline
    info "OS" distro
    info "Host" model
    info "Kernel" kernel
    info "Shell" shell
    info "Packages" packages
}

ascii_distro="Ooonana"
ascii_colors=(3 7 3 3 7 3)
image_source="/usr/share/ooonana/logo.txt"
separator=":"
